language: objective-c

osx_image: xcode7.3

before_install:
  - DEVICE='iPhone 6'
  - IOS_VERSION='9.3'
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "$DEVICE ($IOS_VERSION) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - xcodebuild clean build test -project Workspace/Gollum/Gollum.xcodeproj -scheme Gollum -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=$DEVICE,OS=$IOS_VERSION" | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
