language: objective-c

osx_image: xcode9.1

before_install:
  - DEVICE='iPhone 7'
  - IOS_VERSION='10.3.1'
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "$DEVICE ($IOS_VERSION) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - xcodebuild clean build test -workspace Workspace/Gollum.xcworkspace -scheme Gollum -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,name=$DEVICE,OS=$IOS_VERSION" | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -J "^Gollum$"

